import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

export default function TermsAndConditions() {
    return (
        <main className="min-h-screen bg-white">
            <Navbar />
            <div className="pt-24 pb-16 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
                <h1 className="text-4xl font-bold text-slate-900 mb-8">Terms & Conditions</h1>
                <div className="prose prose-slate max-w-none space-y-6 text-slate-600">
                    <p><strong>GateFare US LLC Terms and Conditions</strong></p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">The Basics</h2>
                    <p>We get it, legal documents can be long and thorough. Here's the simple version:</p>
                    <ol className="list-decimal pl-6 space-y-2">
                        <li>We're the middleman between You and the travel providers. We don't actually provide the trips or flights ourselves.</li>
                        <li>Read the fine print from each provider, especially about changes and refunds. Their rules apply.</li>
                        <li>We'll keep your personal information private and secure. Check our Privacy Policy for details.</li>
                        <li>You need to have valid travel documents like passports and visas. We're not responsible if You can't travel due to lacking documentation.</li>
                        <li>If You encounter any issues with the quality of the travel services, please note that these are provided by the travel supplier (e.g. the airlines) and they are best equipped to address and resolve your concerns.</li>
                    </ol>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">1. Introduction</h2>
                    <p>1.1. GateFare US LLC. is a travel intermediary incorporated in 2025 in the state of Wyoming (US) owning the website www.Gatefare.com (the “Platform”).</p>
                    <p>1.2. We provide an online platform that enables customers to book travel services from various third-party suppliers. We act as an intermediary between the customer and the travel supplier. The travel suppliers, not Us, are responsible for providing the actual travel services purchased by customers through the GateFare platform.</p>
                    <p>1.3. These general Terms and Conditions (“T&Cs”) apply between You (“You” or the “Customer”) and Us, the operator of the Platform and are applicable to services offered and provided by Us through the Platform or by other means (e.g. through contact with our customer support team).</p>
                    <p>1.4. To determine where You are permanently based, We will use specific criteria including, but not limited to, the IP address, the currency selected for payment, and personal information provided during the booking process.</p>
                    <p>1.5. We retain the right to modify these T&Cs at any time, without prior notice.</p>
                    <p>1.6. It is requested that You read these T&Cs carefully prior to using the Platform and ask Us any questions You have about them, and/or consult an attorney if desired, before You agree to be bound by them. You acknowledge having read and accepted these Terms & Conditions (including their Cancellation Policies, Liability Limitations, and Binding Arbitration Provision) before making a booking, and have accepted the same by checking the box “I confirm that I have read and accept the Terms & Conditions and Privacy Policy of www.Gatefare.com, including the Airline Conditions and Fare Rules. I understand that my payment details are not shared with the airline (what it means), and I confirm that all personal information I provided for this booking is accurate and complete.” You agree to be bound by these T&Cs. Without this affirmative acceptance, the processing of a booking is not possible. If You do not accept these T&Cs, We ask that You refrain from using the Platform and/or making a booking.</p>
                    <p>1.7. You must be at least 18 years old and use the Platform for personal purposes. "Personal purposes" means You are an individual booking travel for yourself or family, not for a company or business purposes.</p>
                    <p>1.8. The Platform is intended exclusively for personal use by individual consumers as defined above. Travel agencies, travel agents, and any other individuals or entities acting in a commercial or professional capacity are expressly prohibited from accessing or using the Platform to make bookings or for any other purposes. Unauthorized use of the Platform by such parties may result in the cancellation of bookings, suspension of accounts, and appropriate legal action.</p>
                    <p>1.9. For flights and third-party services offered on the Platform, We operate strictly as an intermediary, facilitating travel services between You (the "Customer") and the service provider (airlines, travel operators, etc.).</p>
                    <p>1.10. If you are a consumer permanently based outside of the U.S. Territory using the Platform, your contractual partner is GateFare US LLC, a Wyoming based LLC located at 30 N Gould St Ste R Sheridan, WY 82801 USA, and your relationship will be governed by U.S. law.</p>
                    <p>1.11. GateFare US LLC DBA: GateFare is registered with the State of Wyoming as Seller of Travel. Registration No. 2025-001821550.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">2. Intermediation of Travel Services</h2>
                    <p>2.1. For the flight and airline services, and in general for third party services offered on the Platform, collectively termed "Travel Services", our role is strictly that of an intermediary. In this capacity, our responsibilities are confined to the intermediation of Travel Services between You and third-party entities, including but not limited to airlines, travel operators and other travel service providers, hereinafter referred to as "Service Provider".</p>
                    <p>2.2. When You purchase Travel Services through our Platform, it is formalized into an agreement directly with the Service Provider(s). We do not enter into the contractual relationship relating to the Travel Services that You purchase, unless expressly indicated as such.</p>
                    <p>2.3. When You make a booking through the Platform, the contractual agreement for the Travel Services will be established between You and the Service Provider(s), unless explicitly stated otherwise, and not between Us and You.</p>
                    <p>2.4. We encourage You to check and read carefully the terms and conditions from each Service Provider before purchasing its products or services, especially those relating to change and cancellation fees.</p>
                    <p>2.5. When You are using the Platform to purchase Travel Services, You grant Us authorization to act as your mediator with the corresponding Service Provider(s). This includes mediating the payment for these Travel Services, ensuring a seamless transaction between You and the Service Provider(s). Upon successful payment, You will receive a confirmed ticket issued by the Service Provider. Please be aware that the final price for the Travel Services may encompass a service fee for the mediation services We provide in facilitating the agreement between You and the relevant Service Provider.</p>
                    <p>2.6. In case You are given the opportunity to express special requests when booking your flight (such as special meals, disabled facilities or child seats), We'll forward them to the appropriate Service Provider. Nonetheless, We cannot guarantee that the Service Provider will be able to meet these particular demands. We may apply a service fee for the processing of these special requests.</p>
                    <p>2.7. The actual execution and quality of the Travel Services mediated through the Platform solely rest with the relevant Service Provider. In our capacity as intermediaries, We do not assume any responsibility for the provision of Travel Services. We also make no representations or warranties, whether expressed or implied, regarding the suitability or quality of Travel Services mediated on the Platform. For any claims or issues related to the performance or non-performance of the Travel Service, the Service Provider is the responsible party to address.</p>
                    <p>2.8. Should You elect to directly request changes or modifications to your reservation with an airline or other Service Provider, please be advised that We cannot guarantee or take responsibility for the outcome of such requests. We will not be liable for any alterations, including cancellations or changes, to your reservation that result from your direct engagement with the Service Provider.</p>
                    <p>2.9. Please note that currently We communicate only in English by phone, email and chat.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">3. Validity and Application of Terms and Conditions</h2>
                    <p>3.1. In relation to Travel Services arranged between You and a Service Provider (to which We are never a participating party), the general terms and conditions of the relevant Service Provider (such as conditions of carriage or the like), as issued by the Service Provider apply. The Service Provider terms may be provided to You by Us and/or the Service Provider during the booking process or may be requested by You directly from the Service Provider. As the Service Provider Terms may encompass provisions related to liability, cancellations, changes, refunds (if they apply), and other limitations, We highly advise You to conduct a comprehensive review of these terms. Please be aware that GateFare US LLC bears no responsibility if you should neglect to read, understand, or comply with any of the Service Provider terms.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">4. GateFare US LLC Services</h2>
                    <p>4.1. At times, in addition to the mediation services, We might make available to You other services for purchase through the Platform. The specific conditions governing some of these services are outlined ANNEX 1 “GateFare US LLC own Services”.</p>
                    <p>4.2. The terms governing some of these Services (e.g. "Premium Assistance", "Flexible Ticket", among others) are instead available in their respective terms and conditions, which are presented to You at the time of purchase and are also accessible from your personal area. The terms associated with these individual services may, in certain instances, supersede or modify the general terms of service laid out in this document. In any situation where there is a discrepancy or conflict between the general T&Cs and those of the specific service, the provisions of the specific service's terms and conditions shall prevail. We strongly recommend that You review these specific terms thoroughly when availing of any such service.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">5. Contact Details</h2>
                    <p>5.1. In some instances, it might be necessary for Us to contact You, for example in case of subsequent changes to the Travel Services that you've acquired. Therefore it is crucial that You provide accurate contact information, including your telephone number and email address. Furthermore, We recommend that You continuously check for messages from Us. Also, You are required to meticulously review all the details You provide when submitting your booking request, including ensuring that your full name corresponds to your identification card, and that You supply the accurate email address and phone number before completing your booking. Please be aware that subsequent change requests may incur substantial additional costs.</p>
                    <p>5.2. It is also your responsibility to ensure that You are able to receive our messages. We are not responsible if You do not receive a message from Us due to circumstances beyond our reasonable control, including, but not limited to the following: (i) You gave Us an incorrect email address; (ii) your email settings won’t allow our email to reach You; (iii) your email settings treat our email as spam; (iv) your email inbox is full and cannot receive new messages; (v) your email provider is experiencing technical issues or downtime and (vi) You provided an incorrect or outdated phone number.</p>
                    <p>5.3. It is your responsibility to contact Us immediately if You do not receive your ticket or other booking confirmation within the expected timeframe or if You identify that You have provided incorrect details for your reservation. Failure to notify Us promptly may result in additional costs or complications that We cannot be held liable for.</p>
                    <p>5.4. By providing your mobile phone number and completing a booking with Us, You consent to receive SMS messages intended to keep You informed about your travel arrangements. This may include booking confirmations, flight or accommodation updates, payment confirmations, itinerary changes, and other critical notifications. The frequency of these messages depends on the nature of your booking and the communication required to support it. Standard message and data rates may apply as determined by your mobile carrier.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">6. Mediation of Flights</h2>
                    <p>6.1. With respect to the flights offered on the Platform, We solely serve as intermediaries. The contract for the provision of the flight services is directly established between You and the respective airline. We do not assume any contractual responsibility pertaining to the execution or non-execution of your flight. The operating airline holds exclusive responsibility for the performance or non-performance of your flight.</p>
                    <p>6.2. Following the submission of your booking request, You will receive an email from us, acknowledging the receipt of your request. This email signifies the formation of the mediation contract between You and Us. Please note that once the booking request is submitted, it becomes irrevocably binding on your part for a period of 48 hours. If, for any reason, You do not receive this email within one hour of finalizing your booking request, and We have not reached out to You via email or telephone to report any issues, We kindly request that You get in touch with Us for the purpose of verification but we are not bound for any kind of refund for this.</p>
                    <p>6.3. Once the tickets that You requested have been issued by the airline(s), You will receive an order confirmation email containing the itinerary of your travel. This marks the point at which a legally binding contract between You and the respective airline(s) has been formalized. In some cases, You may receive two booking confirmations – one from Us and another from the respective airline. If You receive two booking confirmations, please utilize the airline's booking confirmation for your check-in.</p>
                    <p>6.4. Please be advised that between the moment You receive our email acknowledging the receipt of your booking request and the moment You receive the order confirmation email containing your travel itinerary, your flight order is in the process of confirmation with the supplier. During this interim period, GateFare US LLC is unable to address queries or accommodate requests for changes from the Customer, as the flight order has not yet been confirmed with the airline. This is a critical phase where the booking is being finalized, and any modifications or inquiries can only be effectively managed after the issuance of the order confirmation email, at which point the contractual agreement with the airline is established.</p>
                    <p>6.5. While mediating Travel Services provided by airlines, We may not always have guaranteed access to the airline's booking system. In such instances, We may represent your interests in finalizing the contract between You and the airline. Additionally, We may request that You directly communicate with the respective airline for inquiries regarding bookings, modifications, or cancellations of your reservation.</p>
                    <p>6.6. Flight prices and seat availability displayed on the Platform are defined by the relevant Service Provider. If the Service Provider makes changes beyond our control, such as alterations to prices, seat availability, flight schedules, or other factors, after you've submitted a booking request but before the contract with the Service Provider becomes binding, the contract will not be activated, and your payment will be refunded. In these cases, We may still reach out to You and present the option to accept the adjusted price during regular operating hours.</p>
                    <p>6.7. Our Platform allows You to customize and combine various individual services. In such scenarios, You engage Us to facilitate the booking of diverse travel offerings from different providers. The specific suppliers involved will be transparently displayed to You during the booking process before finalizing your reservation. When You assemble individual services, it doesn't create a travel contract between You and Us. Instead, You enter into separate agreements with each service provider. Here, We merely act as a facilitator for each individual travel service You select.</p>
                    <p>6.8. The information below outlines general policies and procedures typically applied by airlines regarding booking, check-in, baggage and other common aspects of air travel. However, any airline's specific terms and conditions supersede the general information provided here. Travelers should review each airline's applicable rules before booking.</p>

                    <ol className="list-decimal pl-6 space-y-4">
                        <li><strong>Minors:</strong> We do not facilitate bookings for unaccompanied minors. Children under the age of 18 must be accompanied by an adult for their journey. Some countries and airlines may require children under 18 to travel with a legal guardian, and certain airlines may request proof of age, such as a birth certificate.</li>
                        <li><strong>Infants and Child bookings:</strong> for information regarding travel conditions for children without separate seats, please reach out to the airline directly. Generally, children above 2 years of age require individual seats, while infants aged 0 to 2 years travel without a designated seat. If an infant turns 2 years old during the trip, You must book a child ticket for the entire journey. Please note that infant tickets cannot be booked before the child's birth, as the provided name and birthdate must match the details on the passport. We are not responsible for any expenses resulting from booking the incorrect ticket type initially.</li>
                        <li><strong>Pregnant Travelers:</strong> some airlines do not allow passengers past their 28th week of pregnancy to travel on outbound or return flights. Pregnant travelers should verify with both their physician and the airline that they are fit to fly before booking. Airlines may require documentation from the passenger's doctor.</li>
                        <li><strong>Flight schedule and Check-In Deadlines:</strong> all departure times listed are local to the originating airport. Arrival times are local to the destination airport. Next-day arrivals are generally shown with a "+1" on the timetable. Schedules are preliminary and may change without notice after the ticket has been issued; reasons for these changes include air traffic control, weather or airline operations. Please ensure to reconfirm flight times before departure. Passengers must adhere to the check-in times required by their airline to avoid denied boarding. Airlines may refuse transport to passengers who arrive late for check-in. Some airlines strongly encourage online check-in through their website and may charge fees for manual check-in at the airport counter.</li>
                        <li><strong>Bookings with multiple segments:</strong> some roundtrip or one-way tickets may have multiple segments. Most airlines require tickets to be used in the booked sequence per airline rules. Failure to fly a segment can prompt airlines to cancel the remaining segments. For roundtrip tickets, no-shows on outbound flights often lead to cancellation of the return leg by the airline. You agree not to purchase a round-trip ticket that You plan to use only for one-way travel. You further agree not to purchase a ticket or tickets containing flight segments that You will not be using, such as a "point-beyond", "hidden-city", or "back-to-back tickets". You agree to indemnify GateFare US LLC against any airline claims for the difference between the full fare of your actual itinerary and the value of the ticket or tickets that You purchased.</li>
                        <li><strong>Purchase of combined one-way tickets:</strong> in some instances, One-Way Tickets can be combined and purchased as Round Trip itineraries booked as two separate one-way tickets instead of a roundtrip fare. If purchased separately, each one-way ticket is subject to its respective airline's policies for changes, cancellations, delays, and schedule disruptions like strikes. Airlines treat one-way tickets independently even if booked together as part of the same itinerary. Passengers should review both airlines’ rules prior to ticketing. Airline tickets booked under separate booking numbers are always treated as discrete, independent itineraries by carriers.</li>
                        <li><strong>Double bookings:</strong> A double booking occurs when an airline has issued more than one reservation for the same passenger on the same flight or overlapping flights. If You find yourself in possession of a double booking, the airline has the prerogative to cancel the associated trip(s). A similar outcome may also arise if these reservations were generated through different travel agencies. Please note that We do not bear liability for airline-initiated cancellations or denied reimbursements in instances where a double booking is suspected.</li>
                        <li><strong>Damaged or lost luggage:</strong> as an intermediary, We do not assume liability for lost or damaged luggage. If You encounter any issues with your luggage, it is essential that You report them immediately to the airline's representative at the airport. The airline is liable to You for the baggage You entrust to it only for the compensation contemplated in the international conventions or other relevant statutes. In the event of damage, late forwarding, theft or loss of luggage, You should contact your airline and declare the damage, absence or loss of your personal effects before leaving the airport, and then submit a declaration, attaching the originals of the following documents: the travel ticket, the baggage check-in slip, and the declaration. It is recommended that You take out an insurance policy covering the value of your items.</li>
                        <li><strong>Ground Transportation and Accommodations:</strong> usually, expenses related to ground transportation and overnight stays during your journey are not covered by the flight ticket price. It is your individual responsibility to confirm ground transportation schedules and associated expenses.</li>
                        <li><strong>Connection times between flights:</strong> standard tickets reserved through the Platform have minimum connection times set by airlines. If a flight leg experiences a delay that results in a missed connection, the airlines are obligated to facilitate your journey to your ultimate destination. In the case of separate ticket bookings, airlines do not assume liability for missed connections due to delays. Consequently, it is your responsibility to confirm that the connection time is sufficient according to the airlines and airports. Any supplementary expenses incurred due to missed connections will not be subject to reimbursement.</li>
                    </ol>

                    <p>6.9. If you are a consumer permanently based outside of the U.S. Territory, the following applies - Exclusion from the 24-Hour Refund Policy: In accordance with prevailing laws, You recognize and accept that, under U.S. federal guidelines, GateFare US LLC, given its status of intermediary, isn't obligated to offer or provide ticket cancellations or refunds. This remains true even if such a request is submitted within 24 hours of making a reservation or during any other timeframe outlined in relevant legislation. For clarity, GateFare US LLC, as a third-party agent, is not bound by the 24-hour booking refund directive established by the U.S. Department of Transportation.</p>
                    <p>To exercise your right of withdrawal (where applicable), notify Us before the deadline via the call on the number available at www.GateFare.com or by sending a written notice to GateFare US LLC – “support@gatefare.com”. Please include Your Order ID in the communication. As the Customer bears the responsibility for exercising the right of withdrawal within the set time frame, it is advisable to use a reliable means of communication for this purpose.</p>
                    <p>6.10. The flight times listed on your booking confirmation might vary from the date of your booking to your actual travel date. We advise checking with your airline at least 3 days prior to the scheduled departure to confirm the timing of your flight and any connections. Additionally, We recommend verifying the specific terminal and any potential changes at the airport a day before your travel. We're not responsible for any alterations made by the airline or any inconveniences at the airport, nor for any associated costs that might arise due to these changes.</p>
                    <p>6.11. Changes and cancellations requested by You: Flight booking adjustments (like altering passenger details, destinations, and travel dates) as well as cancellation refund policies are defined by the corresponding airline, your main agreement holder for flight services. As intermediaries, We hold no control over these policies.</p>
                    <ol className="list-decimal pl-6 space-y-4">
                        <li>Should You request to modify your reservation or seek a cancellation refund, We can step in to manage the request for you, as long as the airline's terms allow for such modifications or refunds. When arranging these supplementary services, We'll notify You of any associated terms and charges. For a list of our fees, please refer to Section 110 on this document.</li>
                        <li>For Us to manage your change requests, We must receive such requests a minimum of 5 working days before travel begins. If You need to request changes on a shorter notice, We advise reaching out to the respective airline directly.</li>
                        <li>If You wish to request a schedule change for your flight, please note that You cannot choose a new flight departing within 72 hours from the time You submit your request to Us. This requirement ensures sufficient processing time and coordination with the respective airline.</li>
                        <li>We do not support partial cancellations of your booking due to our role as an intermediary between You and the Service Provider. If You wish to request a partial voluntary cancellation You are advised to contact the airline directly for further assistance. However, please note that We cannot guarantee any outcome or assume liability for any cancellation that You have requested directly to the Service Provider.</li>
                        <li>In cases where an amendment to passenger details is permitted according to airline policies, as well as our T&Cs, only minor corrections are allowed (e.g., spelling errors or missing characters). Full name changes or significant alterations to passenger details cannot be processed, as airline tickets are non-transferable. We recommend reviewing all details carefully at the time of booking to avoid such issues.</li>
                    </ol>
                    <p>6.12. Missed Flight or No-Show: Should You fail to show up for or miss your flight, You give Us permission to seek potential refunds from the airline on your behalf. While We have the right to do this, it's not a requirement. Your entitlement to pursue unclaimed refunds directly from the airline is still intact.</p>
                    <ol className="list-decimal pl-6 space-y-4">
                        <li>Should We secure refunds for you, our fees will be subtracted from the retrieved amount. We'll hold onto any refunds, after deducting our charges, for a duration of 12 months from the flight date. You can ask for a transfer of the remaining balance anytime within this 12-month window by reaching out to our customer service. For a list of our fees, please refer to Section 110 on this document.</li>
                    </ol>
                    <p>6.13. As an intermediary, We strive to provide accurate baggage allowance information based on the information available to Us at the time of booking. However, the baggage allowances displayed on the Platform are indicative and may not fully reflect the actual allowance provided by the airlines. It is your responsibility to verify the exact baggage allowance for your ticket directly with the airline before making any additional baggage allowance purchases or requesting any refunds related to baggage. We are not liable for any discrepancies between the indicative information provided on the Platform and the airlines’ actual baggage policies, and no refunds will be issued for additional baggage purchases made based on this indicative information.</p>
                    <p>6.14. Additional and oversized baggage fees: Most airlines have their own policy regarding baggage. Always check with your airline before You fly for their most current baggage fees and rules.</p>
                    <p>If We do not have info for your flight, We recommend that You check with your airline ahead of time for any weight restrictions and additional charges relating to checked baggage. You will be responsible for paying to the airline any additional charges for checked or overweight baggage, including, but not limited to, golf bags and oversized luggage. If You exceed the weight limit set by your airline, and excess weight is permitted, You must pay a supplement directly to the airline at the airport.</p>
                    <p>6.15. Stop-Overs: Direct flights may be “non-stop” or may involve one or more stop-overs (in the latter case this means the same flight by the airline, because the flight number remains the same). The same applies to connecting flights that may be subject to crew changes. When You reserve a flight involving a stop-over in a town, and the second flight takes off from a different airport to the airport of arrival, ensure that You have sufficient time for reaching the second airport. The journey to the other airport is at your own expense. We will not be able to reimburse You for these costs, nor will it be liable if You miss the second flight.</p>
                    <p>6.16. Problems related to the issuance of e-tickets: As of June 1st, 2008, the International Air Transport Association (IATA) imposed rules with regard to the issuing of air travel tickets. As of that date, travel agencies and airlines have an obligation to only issue travel tickets via electronic means. Due to technical constraints to do with airline’s restrictions in relation to certain requirements (infants under the age of 2, inter-airline agreements, groups, etc.), it may be impossible to issue an electronic ticket. Therefore, though a flight may be shown as available, it might prove impossible for Us to honor your reservation. This situation, which is outside our control, will not result in liability on our part.</p>
                    <p>If We cannot issue You an e-ticket, We will contact You to propose an alternative route solution. This could involve a different tariff and/or additional costs for which You would be responsible. In the event of the absence of an alternative solution, your refusal to pay any tariff difference, or if the issuance of tickets proves impossible, We would be forced to cancel your reservation at no cost to you. We will provide You with a full refund after determining that there is no alternative solution possible.</p>
                    <p>6.17. When You make a booking through the Platform, You acknowledge and accept that, in certain cases, GateFare US LLC may place the booking through a third-party supplier rather than directly with the airline. Accordingly, when an airline communicates that a refund has been issued, the refunded amount may have been remitted to the third-party supplier, and not directly to GateFare US LLC. We will make every commercially reasonable effort to recover any applicable refund from the supplier and pass it on to You in accordance with these Terms and Conditions. However, You acknowledge that GateFare US LLC may not always be the direct recipient of the refunded amount, and that a reasonable processing period may be required to coordinate with the supplier and complete the refund process.</p>
                    <p>6.18. By completing a booking on the Platform, You acknowledge and accept that it is not possible to add additional passengers to an existing reservation through GateFare US LLC after the order is confirmed. This includes, but is not limited to, any requests to add infants, children, or any other category of passenger who, under airline policies, cannot travel alone or independently make a booking.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">7. Selected Seat Conditions</h2>
                    <p>7.1. If the selected flight includes the option to choose seats, GateFare US LLC may offer You the ability to request specific seats during the booking process, subject to the terms listed below.</p>
                    <p>7.2. By using the seat selection feature, You authorize GateFare US LLC to submit seat requests to the relevant airline on Your behalf and on behalf of any other passengers included in the booking.</p>
                    <p>7.3. By requesting specific seats, You confirm that You have reviewed and accepted the applicable seat assignment policies and transportation conditions of the selected airline, including any limitations or restrictions, for all passengers under the reservation.</p>
                    <p>7.4. While GateFare US LLC will transmit Your seat preferences to the airline, final seat allocation is at the discretion of the airline. If the requested seat is unavailable, the airline may assign an alternative with comparable characteristics (e.g., window seat, extra legroom, front row, etc.). For group bookings, efforts will be made to preserve seat proximity where possible.</p>
                    <p>7.5. If the selected seat cannot be confirmed due to reasons beyond GateFare US LLC control (e.g., technical failure, airline denial), You will be notified in advance of departure and any amount paid specifically for the unfulfilled seat selection will be refunded. In such cases, GateFare US LLC shall not be liable for the inability to secure the preferred seat.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">8. Timetable Changes and Cancellation by Airlines</h2>
                    <p>8.1. The airline with which You have an agreement may have the authority to modify or cancel your reservations. Once informed by the airline of any alterations, We will notify You promptly.</p>
                    <p>8.2. Please note that while GateFare US LLC makes every effort to notify Customers of any involuntary schedule changes made by airlines, there may be instances where changes occurring within 24 hours prior to departure might not be intercepted and relayed to You in a timely manner. Given the proximity to the departure time and potential communication delays, We strongly advise all Customers to periodically check the airline's official website or contact the airline directly in the hours leading up to departure to ensure that they are aware of the most current flight information. GateFare US LLC decline all responsibilities for missed flights or any resulting consequences due to involuntary schedule changes made by airlines within the 24-hour window before departure.</p>
                    <p>8.3. In response to schedule changes and/or Airport changes initiated by the airline, GateFare US LLC adopts the following procedures based on the extent of the change:</p>
                    <ol className="list-decimal pl-6 space-y-4">
                        <li>If the airline alters the flight schedule three (3) hours or less in total, GateFare US LLC will automatically accept this schedule change on behalf of the Customer. This policy is in place to streamline the process and ensure minimal disruption to your travel plans.</li>
                        <li>In the event of a schedule change by the airline that exceeds three (3) hours in total, or in the event that the airline changes the departure or arrival airport of your flight, GateFare US LLC will present the Customer with alternative options made available by the airline at that time. Due to the time-sensitive nature of flight schedule changes, GateFare US LLC will provide a specific timeframe within which the Customer must provide their acceptance of one of the presented alternatives.</li>
                        <li>It is crucial that Customers respond within the given timeframe to facilitate a seamless adjustment to their travel itinerary. In the absence of an explicit reply from the Customer within this period, GateFare US LLC reserves the right to make a decision on the Customer's behalf regarding the schedule change. This measure ensures the preservation of the Customer's travel arrangements and adherence to the airline's conditions and availability.</li>
                        <li>Customers are advised to maintain open lines of communication with GateFare US LLC during this process to ensure that their preferences are considered and to avoid any potential misunderstandings regarding their travel itinerary.</li>
                    </ol>
                    <p>8.4. In the event of a timetable change or cancellation initiated by the airline, should You request Us to seek an alternative flight option beyond what the airline has provided, We will try to handle the request on your behalf, contingent upon the airline's conditions. While We do not guarantee sourcing alternative flight options beyond those already provided by the airline, in specific cases and at our discretion, We may assist in finding other options. Please be aware that GateFare US LLC may apply a service fee for assisting You during a change or cancellation initiated by the airline. For a list of our fees, please refer to Section 11 on this document.</p>


                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">9. Preservation of Rights / Waiver</h2>
                    <p>9.1. At no point should our actions be interpreted as forgoing or surrendering any protections, disclaimers, commitments, terms, or any element of this contract. Specifically, if We grant You a refund, allow modifications, accept a cancellation, or make any other allowances concerning our Travel Services, it does not imply We are waiving any of our contractual rights or terms.</p>
                    <p>9.2. No delay or failure by either party to exercise or enforce at any time any right or provision hereof will be considered a waiver thereof of such party's rights thereafter to exercise or enforce each and every right and provision hereof. No single waiver will constitute a continuing or subsequent waiver. GateFare US LLC does not guarantee it will take action against all breaches of our T&Cs. No waiver of any provision hereof will be effective unless it is agreed by both the parties.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">10. Travel Documentation and Entry Requirements</h2>
                    <p>10.1. It's essential to note that passport, visa, and health requirements may vary, so You should consult the pertinent authority (like an embassy or consulate) well before your travel date. You are responsible for having a valid passport and, if necessary, the appropriate visa. Don't forget to account for any transit stops in your itinerary, as they might also necessitate a visa. Obtaining a visa can be a lengthy process, so early application is recommended. We bear no liability for individuals lacking the proper documentation.</p>
                    <p>10.2. Every destination comes with specific entry criteria, vaccination requirements, and other regulations that might differ based on the traveler's nationality. Gathering this information is your responsibility. We won't be held accountable for any issues resulting from non-compliance with these official guidelines. Thus, We strongly advise You to thoroughly check the requirements of your intended destination and any transit countries, including the time required to complete any necessary procedures.</p>
                    <p>10.3. Most international travel requires a passport valid until at least six (6) months beyond the scheduled return date. Further information on entry requirements can be obtained from your national authority responsible for foreign affairs, or directly from the destination country's website. Some countries require You to be in possession of a return ticket or exit ticket and have sufficient funds, etc. Similarly, certain countries require that You produce evidence of insurance/repatriation coverage before it will issue a visa.</p>
                    <p>10.4. You must carefully observe all applicable formalities and ensure that the surnames and forenames used for all travelers when making a booking and appearing in their travel documents (booking forms, travel tickets, vouchers, etc.), correspond exactly with those appearing on their passport, visas, etc.</p>
                    <p>10.5. WE CANNOT ACCEPT RESPONSIBILITY IF YOU ARE REFUSED PASSAGE ON ANY AIRLINE, TRANSPORT OR ENTRY INTO ANY COUNTRY DUE TO THE FAILURE ON YOUR PART TO CARRY OR OBTAIN THE CORRECT DOCUMENTATION OR IMMUNIZATIONS. IF FAILURE TO DO SO RESULTS IN FINES, SURCHARGES, CLAIMS, FINANCIAL DEMANDS OR OTHER FINANCIAL PENALTIES BEING IMPOSED ON US, YOU WILL BE RESPONSIBLE FOR INDEMNIFYING AND REIMBURSING US ACCORDINGLY.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">11. Service Fees</h2>
                    <p>11.1. GateFare US LLC imposes non-refundable service fees for its mediation services.</p>
                    <p>11.2. The service fees set by GateFare US LLC can vary based on the products or services in your order, the channel used, and other pertinent factors.</p>
                    <p>11.3. The currency in which the service fee is applied will depend on the currency used during the transaction of the original reservation.</p>
                    <p>11.4. We retain the right to charge the service fee (or a portion thereof) upfront at the time of the request. This approach helps ensure partial compensation for the activities and associated costs GateFare US LLC undertakes in response to the Customer's request.</p>
                    <p>11.5. As an intermediary, GateFare US LLC can apply the following service fees:</p>
                    <ol className="list-decimal pl-6 space-y-4">
                        <li>Flight Cancellation requested by Customer: $150 (or €150 or £130) per request</li>
                        <li>Changes to existing tickets requested by Customer prior to current scheduled trip departure: $150 (or €150 or £130) per request</li>
                        <li>All other requests related to the Travel Services purchased by the Customer: $30 (or €30 or £25) per passenger per leg of the trip. Examples of these requests include, but are not limited to: managing changes or cancellations initiated by the airlines, providing manual assistance for tasks such as making a new booking or adding passengers, assisting with alternative flight options when the airline changes or cancels a scheduled flight, handling baggage requests, name changes and corrections, seating arrangements, and other extra services.</li>
                    </ol>
                    <p>10.6. Be aware that any modifications and/or refunds are governed by the airline's policies and fare rules. There may be additional fees imposed by the airline, over which We, acting as intermediaries, have no control. If the requested change results in a higher ticket price, or if the alteration causes the passenger to be ineligible for a special rate, any such additional costs will be the responsibility of the Customer.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">12. Pricing Errors</h2>
                    <p>12.1. In rare instances, there may be an error in the pricing. Obvious pricing errors are not binding. An obvious pricing error is one that is glaring and manifest, where it is clear that no reasonable person would consider the price as normal. Under such circumstances, We reserve the right to cancel the booking without any penalty and refund the charged amount. We may offer the User the option to retain the booking at the correct price and pay the price difference.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">13. Refund Procedures and Limitations</h2>
                    <p>13.1. Refunds are handled according to the Service Provider's terms and conditions. If You qualify for a cash refund, it will be issued using the initial payment method from your booking. Additionally, if you're eligible for a cash refund, We may offer You the alternative of receiving a voucher instead. Be aware that airfares consist of various components, and not all of them might be refundable. Therefore, even if You qualify for a refund based on the Service Provider's policies, the amount returned may not match the total You initially paid for your booking.</p>
                    <p>13.2. For reasons of transactional security and fraud mitigation, We are not permitted to process a monetary refund to the original payment method absent the Customer’s explicit confirmation. Accordingly, the Customer is required to affirmatively select a preferred refund method within thirty (30) calendar days from the date on which the refund options are communicated. In the event that the Customer fails to provide such confirmation within the specified period, We shall be deemed unable to effect a direct refund to the original form of payment, and a voucher of equivalent value will be issued in lieu thereof, redeemable against future bookings.</p>
                    <p>13.3. All refunds are issued by the relevant Service Provider. As an intermediary, We have no control over the Service Provider's processing times.</p>
                    <p>13.4. As We operate as an intermediary, We'll initiate a refund only once the corresponding funds have been received from the pertinent Service Provider. Please note that all refunds will be processed after deducting our service fees.</p>
                    <p>13.5. Your booking's total price comprises the Travel Service(s) price, any add-on products, and our service fees. Please be aware that our service fees aren't refundable, as they cover our intermediation services, deemed complete once your booking is confirmed. Refunds for add-on products from third party Service Providers are contingent upon our receipt of corresponding refunds from them. Any add-ons offered by Us are also not refundable except where prohibited by law.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">14. No Show</h2>
                    <p>14.1. If You choose not to use the flight ticket or fail to arrive at the boarding gate on time, You may be entitled to a partial refund of the unused ticket, depending on the fare purchased. Upon purchasing through our Platform, You authorize Us to take all necessary actions, on a non-exclusive basis, to request and obtain the refund from the airline on your behalf for the unused flight segments (hereinafter referred to as the "NoShow Mandate"). The Company accepts the NoShow Mandate from the moment it initiates the refund request with the airline. The recovered amounts will be held by the Company with the utmost care until You request them by contacting Us through our standard support channels available in Your “My Trips”. If the refund is available, it will be credited to You using the same payment method used during the purchase process, unless otherwise agreed between You and the Company. It is clarified that the amount held will not accrue any interest under any circumstances.</p>
                    <p>14.2. If the refund is not expressly requested within 3 months from the scheduled departure date of the unused flight, the amount will be converted into a voucher, which can be used for booking a new flight on the Website within 12 months from the issuance date. The voucher is personal, non-transferable, and cannot be converted into cash. The Company charges a fee for managing the NoShow Mandate, as specified in Section 11. Additionally, You authorize the Company to deduct these management fees directly from the refund obtained from the airline.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">15. Payment, Currency and Credit Card Considerations</h2>
                    <p>15.1. Payment for Travel Services is managed either directly by Us or by affiliates within our corporate network, in collaboration with our designated payment service providers who oversee the payment functionalities, or by the Service Provider. Any payment details provided by our Customers are encrypted and securely transmitted to our payment service providers.</p>
                    <p>15.2. Should We have grounds to believe that a payment may involve fraudulent activity, We reserve the right to decline processing that payment. Verification of the payment may be required if any illicit activity is suspected. We reserve the right to report to law enforcement authorities any act of payment fraud.</p>
                    <p>15.3. In the event that We have justifiable suspicion that a reservation has been made with fraudulent intent, We reserve the right to cancel said reservation. Following the cancellation, a refund will be issued to the Customer.</p>
                    <p>15.4. To process your payment, please ensure that sufficient funds are available. If issues arise during the transaction, We will coordinate with our payment service providers to attempt the transaction again. If the transaction cannot be completed, We may contact You for alternative payment options. If the payment continues to remain outstanding, We reserve the right to refer the amount to a debt collection agency.</p>
                    <p>15.5. In certain instances, the billing currency may not match the currency shown for prices and fees on our Platform, especially if specific currencies aren't supported. We'll provide an estimate using an alternate currency that the Platform supports. As a result, when You finalize your booking, the ultimate charge on your payment method might slightly vary due to changes in exchange rates, currency conversion, and potential fees from other involved parties (e.g. the credit card company). Should this apply to your booking, We will notify You during the reservation process.</p>
                    <p>15.6. Based on the specifics of your booking and any additional services selected, the payment might be divided into two distinct transactions: one from Us and another from the Service Provider. The total charged won't exceed the amount displayed on our website. All transactions are subjected to the same stringent security protocols.</p>
                    <p>15.7. Credit Card Billing Address: Credit card payments require a verifiable billing address from the United States, Canada, or other recognized countries.</p>
                    <p>15.8. Non-Dispute Agreement: By electing to pay for travel services with a credit/debit card, You agree not to dispute such charges with your bank under circumstances including, but not limited to, claims of non-receipt of product or services or requests for refunds. Any disputes shall be resolved by contacting Us directly, prior to initiating any bank disputes.</p>
                    <p>15.9. Liability for Payments: You acknowledge liability for all credit card payments and agree not to dispute charges post-purchase once travel tickets or other services have been confirmed via email. You commit to reimburse any chargebacks or credit card disputes in cases where services have been verifiably purchased from our Platform.</p>
                    <p>15.10. Breach of Terms: Initiating a dispute with your credit/debit card issuer constitutes a breach of our T&Cs.</p>
                    <p>15.11. Authorization of Online Transactions: Online credit card transactions are deemed authorized when a Customer, or their authorized representative, accepts these T&Cs and agrees to proceed with the purchase.</p>
                    <p>15.12. Handling of High-Risk Transactions: Transactions identified as high-risk by our systems will not be processed unless cleared by our credit card verification systems. For such transactions, We reserve the right to contact You or your bank to validate the transaction.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">16. Chargebacks and Compensation</h2>
                    <p>16.1. In the event that a Customer initiates a chargeback through their credit card company or bank against any transaction made on our Platform, GateFare US LLC reserves the right to immediately cancel the associated booking with the travel supplier. If We have grounds to suspect that a chargeback has been initiated with fraudulent intent, We reserve the right to take all necessary actions to prevent the suspected user from using our Platform in the future. Customers are encouraged to communicate with our Customer support team to address any concerns before resorting to a chargeback to avoid potential cancellations and loss of funds.</p>
                    <p>16.2. If GateFare US LLC cancels a booking with the travel supplier due to a chargeback initiated by the Customer as described in Clause 15.1, and subsequently receives a refund from the supplier, We will refund this amount to the Customer. However, We reserve the right to deduct a service fee of up to $1,000 from the refund to cover the costs incurred in managing the chargeback process. The remaining refund will be issued to the Customer in the form of a voucher, which will expire 12 months from the date of issuance. This voucher is non-transferable and cannot be exchanged for cash.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">17. Addressing Claims</h2>
                    <p>17.1. Claims relating to performance of Travel Services: If you should have any concerns, comments, or claims about the actual delivery of Travel Services, You should directly communicate with the respective Service Provider with whom You have a contract for that specific Travel Service.</p>
                    <p>17.2. If you are a consumer permanently based in/outside of the U.S. Territory, any claims concerning services provided directly by GateFare US LLC must be made in writing and submitted within three months following the conclusion of your journey at the following address: GateFare US LLC, located at 30 N Gould St Ste R, Sheridan, WY 82801, USA.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">18. Roles, Responsibilities, and Limitations of Liability</h2>
                    <p>18.1. You acknowledge that We serve as an intermediary between You and the Service Provider. We will not be held responsible for any Travel Services you've reserved with any Service Providers, nor for any discrepancies in the data shown on the Platform that originates from these Service Providers.</p>
                    <p>18.2. If a Service Provider is unable to deliver the Travel Service for any cause, including bankruptcy, our role remains as a facilitator. We will only process refunds when We have received corresponding funds from the concerned Service Provider.</p>
                    <p>18.3. By accepting these T&Cs, the Customer grants GateFare US LLC the authorization to act on behalf of the Customer in any bankruptcy proceedings of the Service Provider, including initiating legal actions necessary to protect the Customer’s interests. Such delegation is considered valid, but will only be deemed accepted by GateFare US LLC upon explicit communication of acceptance to the Customer. If GateFare US LLC does not communicate its acceptance, the Customer remains responsible for pursuing their own claims in the bankruptcy process.</p>
                    <p>18.4. Concerning our services, our liability for damages is constrained by the limitations detailed in the T&Cs and as allowed by law. IN NO EVENT SHALL GateFare US LLC BE LIABLE FOR ANY CONSEQUENTIAL, INDIRECT, EXEMPLARY, SPECIAL, INCIDENTAL OR PUNITIVE DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION, DAMAGES FOR ANY LOSS OF OPPORTUNITY OR OTHER PECUNIARY LOSS, EVEN IF GateFare US LLC HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES OR LOSSES, WHETHER SUCH LIABILITY IS BASED UPON CONTRACT, TORT, NEGLIGENCE OR OTHER LEGAL THEORY. We will only be responsible for direct damages you've genuinely experienced, paid, or incurred because of a failure on our part to fulfill our service obligations, up to the total cost of your booking (either for a single incident or a sequence of related incidents). IN NO EVENT SHALL GateFare US LLC’ TOTAL AGGREGATE LIABILITY TO THE TRAVELER FOR CLAIMS ARISING UNDER THIS AGREEMENT EXCEED THE TOTAL AMOUNTS PAID BY THE TRAVELER TO GateFare US LLC UNDER THIS AGREEMENT.</p>
                    <p>18.5. If, due to exceptional events or situations beyond our control (Force Majeure), there are issues with reservations, confirmations, or the delivery of any bookings or services, We are absolved from any legal liabilities stemming from such issues or non-adherence related to the Force Majeure effects. “Force Majeure” refers to any event beyond GateFare US LLC’ reasonable control, including but not limited to severe weather, fire, flood, mudslides, earthquakes, war, labor disputes, strikes, political unrest, natural or nuclear disaster, epidemics, World Health Organization’s advisories and/or alerts, Center for Disease Control’s advisories and/or alerts, U.S. State Department’s advisories and/or alerts, any order of any local, provincial or federal government authority, interruption of power Services, terrorism or any other causes beyond the control of GateFare US LLC. This liability limitation extends to breaches of duty by individuals whose actions We are accountable for under legal regulations.</p>
                    <p>18.6. GateFare US LLC OFFERS VARIOUS TRAVEL SERVICES PROVIDED BY THIRD PARTY SUPPLIERS. GateFare US LLC RETAINS NO OWNERSHIP INTEREST, MANAGEMENT, OR CONTROL OF THOSE THIRD PARTY SUPPLIERS. TO THE FULLEST EXTENT PERMITTED BY LAW, GateFare US LLC DOES NOT ASSUME LIABILITY FOR ANY INJURY, DAMAGE, DEATH, LOSS, ACCIDENT OR DELAY DUE TO AN ACT OR OMISSION OF ANY THIRD PARTIES (INCLUDING THIRD PARTY SUPPLIERS), GOVERNMENTAL AUTHORITY, OR ACTS ATTRIBUTABLE TO YOU YOURSELF, INCLUDING, WITHOUT LIMITATION, NEGLIGENT OR RECKLESS ACTS.</p>
                    <p>18.7. Responsibility for User-Generated Content: although GateFare US LLC facilitates the booking of travel services through its website, it is not responsible for content uploaded by users or third-party travel service providers.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">19. User Behavior</h2>
                    <p>19.1. At our sole discretion, without any obligation to You and without needing any prior notice, We may limit, suspend, deactivate, or cancel your account and/or deny You access to the Portal for any or no reason. Once your account is terminated, deactivated, or suspended, You must stop using the Portal immediately and refrain from creating a new account and/or any new bookings.</p>
                    <p>19.2. You understand and agree that You are solely responsible for adhering to any applicable laws related to your use of the Portal. In your interactions with the Portal, You must not violate any laws, misuse the Portal for unauthorized purposes, infringe upon the rights of any individual or entity, including intellectual property or privacy rights, take actions that could damage or compromise the Portal's security or functioning, misrepresent your identity, breach GateFare US LLC ' security protocols, circumvent any technological measures set by GateFare US LLC or its providers, or tamper with the underlying software of the Portal.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">20. Compliance with Sanctions and Prohibited Transactions</h2>
                    <p>20.1. GateFare US LLC is committed to full compliance with all applicable laws and regulations related to sanctions and prohibited transactions. As such, We do not accept bookings or provide services to individuals, entities, or countries that are subject to sanctions, restrictions, or embargoes imposed by the U.S. Department of the Treasury's Office of Foreign Assets Control (OFAC), the European Union, or any other relevant governing body.</p>
                    <p>20.2. By using our Platform and services, You represent and warrant that neither You nor any entity You represent are listed on any sanctioned parties list compiled by OFAC, the European Union, or other relevant authorities. You also represent that You are not located in, under the control of, or a national or resident of any restricted or sanctioned country or region.</p>
                    <p>20.3. Any bookings or transactions that are found to be in violation of this policy will be canceled, and any payments made will be refunded as per our refund policy. Providing false or misleading information to evade these restrictions may result in legal consequences, and GateFare US LLC reserves the right to report any such violations to the relevant authorities.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">21. Governing Law and Dispute Resolution</h2>
                    <p>21.1. For consumers permanently based in or outside of the U.S Territory, these T&Cs and your use of the Services are governed by the laws of the State of Wyoming, without regard to its conflict-of-law provisions, and disputes will be resolved through binding arbitration in the U.S. Both You and We agree to submit to the personal jurisdiction of a state court located in Wyoming for any actions where the parties retain the right to seek injunctive or other equitable relief to prevent actual or threatened infringement, misappropriation, or violation of a party’s copyrights, trademarks, trade secrets, patents, or other intellectual property rights, as detailed in the Dispute Resolution provision below. You and We hereby agree not to assert, by way of motion, as a defense or otherwise, in any such action, suit or proceeding, any claim that (i) he, she or it is not subject personally to the jurisdiction of such court, (ii) the venue is improper, or (iii) this agreement or the subject matter hereof may not be enforced in or by such court.</p>
                    <p>21.2. This arbitration agreement is part of a transaction involving interstate commerce and is thus governed by the Federal Arbitration Act (FAA). The arbitration will be administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules and Supplementary Procedures for Consumer Related Disputes (AAA Rules), as modified by this Arbitration Agreement. The AAA Rules are available at www.adr.org/Rules.</p>
                    <p>21.3. To begin arbitration, a party must provide the other party with a written Demand for Arbitration as outlined in the AAA Rules. The arbitrator, who will be either a retired judge or an attorney licensed to practice law in Delaware, will be selected by the parties from the AAA's roster of consumer dispute arbitrators. If the parties cannot agree on an arbitrator within seven (7) days of the Demand for Arbitration, the AAA will appoint one in accordance with its rules.</p>
                    <p>21.4. Unless both parties agree otherwise, arbitration will be conducted in the state of Wyoming, United States. If your claim does not exceed $10,000, arbitration will be based solely on documents submitted, unless a hearing is requested or deemed necessary by the arbitrator. For claims exceeding $10,000, the right to a hearing will be determined by AAA Rules. The arbitrator may direct a reasonable exchange of information by the parties, in line with the expedited nature of arbitration.</p>
                    <p>21.5. The arbitrator will issue a decision within the timeline specified by AAA Rules, including essential findings and conclusions. Judgment on the award may be entered in any court with jurisdiction. The arbitrator’s award damages must adhere to the “Roles, Responsibilities, and Limitations of Liability” section of GateFare US LLC T&Cs in terms of types and amounts. Only declaratory or injunctive relief in favor of the individual claimant is permitted. The prevailing party in arbitration may be awarded reasonable attorneys' fees and expenses.</p>
                    <p>21.6. Your obligation to pay any AAA filing, administrative, and arbitrator fees will be as set forth in the AAA Rules.</p>
                    <p>21.7. If GateFare US LLC modifies this Arbitration Agreement after your acceptance, You may reject the change by sending written notice within 30 days of the change becoming effective. By rejecting changes, You agree to arbitrate any Dispute between You and GateFare US LLC under the provisions of this Arbitration Agreement as of your original acceptance date.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">22. Data Protection</h2>
                    <p>22.1. We are fully committed to ensuring the privacy and protection of your personal data. In compliance with the General Data Protection Regulation (GDPR), We have implemented rigorous measures to safeguard your information. For a comprehensive understanding of how We manage, store, and protect your data, We encourage You to review our Privacy Policy. Your trust is paramount to us, and We are dedicated to maintaining transparency about our data practices.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">23. Intellectual Property Provisions for GateFare US LLC</h2>
                    <p>23.1. Ownership of Intellectual Property: All content, including but not limited to logos, brand names, images, designs, text, graphics, software, and any other material found on the Platform, is the exclusive property of GateFare US LLC or its licensors and is protected by U.S., EU and international copyright, trademark, trade secret, and other intellectual property or proprietary rights laws.</p>
                    <p>23.2. Prohibited Use: No part of the Platform, including its content, may be reproduced, copied, modified, transmitted, distributed, or otherwise used for commercial or public purposes without the prior written consent of GateFare US LLC.</p>
                    <p>23.3. Trademarks: The GateFare US LLC logo is related names, logos, product and service names, designs, and slogans are trademarks of GateFare US LLC or its affiliates or licensors. You must not use such marks without the prior written permission of GateFare US LLC. All other names, logos, product and service names, designs, and slogans on the Platform are the trademarks of their respective owners.</p>
                    <p>23.4. Infringement Notice: GateFare US LLC respects the intellectual property rights of others and expects users of the Platform to do the same. If You believe that any content on the Platform infringes upon your copyright, please provide Us with the necessary details so We can take appropriate action.</p>
                    <p>23.5. Changes to Intellectual Property Provisions: GateFare US LLC reserves the right to change, modify, or update these Intellectual Property Provisions at any time without notice. It's recommended that users regularly review these provisions to keep themselves informed.</p>
                    <p>23.6. No Transfer: Nothing in these terms shall be construed to convey to You any interest, title, or license in a GateFare US LLC IP address, domain name, or similar resource used by You in connection with the Platform or the services.</p>
                    <p>23.7. Link: The Platform may include hyperlinks to other Internet resources provided by GateFare US LLC' business partners or third parties. These links are included solely for informational purposes and do not constitute any endorsement or guarantee of the content of these sites by GateFare US LLC. GateFare US LLC has no control over the content, services, information, or products offered on the linked sites and assumes no responsibility for their accuracy, reliability, or updates. Access to such sites is made at the sole risk of the user. The presence of hyperlinks or other external resources on the website does not imply any affiliation or commercial relationship between GateFare US LLC and the owners of the linked sites.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">24. Indemnification Provisions for GateFare US LLC</h2>
                    <p>24.1. Indemnity: You agree to defend, indemnify, and hold harmless GateFare US LLC, its affiliates, licensors, and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these T&Cs or your use of the GateFare US LLC Platform, including, but not limited to, your user contributions, any use of the Platform's content, services, and products other than as expressly authorized in these T&Cs or your use of any information obtained from the Platform.</p>
                    <p>24.2. Cooperation: You agree to cooperate fully in the defense of any claim. GateFare US LLC reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you. You will not, in any event, settle any claim without the prior written consent of GateFare US LLC.</p>
                    <p>24.3. Survival: The indemnification obligations under this section shall survive the termination or expiration of your relationship with GateFare US LLC or your use of the GateFare US LLC Platform.</p>
                    <p>24.5. Limitation: You acknowledge that the indemnities set forth in this section shall apply regardless of the negligence, gross negligence, or failure of the indemnified purpose to meet any duty of care owed to you, and shall extend to claims for which You may be found to be more than 50% negligent.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">25. Access to Customer Travel Information</h2>
                    <p>25.1. To fulfill our obligations as an agent and to support our Customer effectively, We reserve the right to access and retrieve your travel information from the relevant airline's website. This access may be utilized for various purposes originating from our role as intermediary, including but not limited to, verifying the accuracy of travel details and, at our sole discretion, facilitating the check-in process on your behalf. Notwithstanding, this provision does not constitute a commitment or obligation by GateFare US LLC to perform web check-in on your behalf in every instance.</p>
                    <p>25.2. By using our Platform and services, You grant Us explicit permission to access and utilize your travel information available on the airline's website as necessary to provide the aforementioned support and services. Additionally, You acknowledge and agree that We may use this information to defend ourselves against any potential payment disputes or legal actions You may initiate against Us.</p>
                    <p>25.3. GateFare US LLC will take all reasonable measures to ensure that any access to your travel information is conducted securely and in accordance with our Privacy Policy.</p>

                    <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">26. Additional Provisions</h2>
                    <p>26.1. Dangerous substances: U.S. Federal regulations prohibit the transportation of dangerous substances on aircraft, whether in your baggage or on your person. Violating this rule can lead to a prison sentence of up to five years and fines exceeding $250,000 (49 U.S.C. 5124). These dangerous materials encompass explosives, compressed gasses, flammable liquids and solids, oxidizers, toxins, corrosives, and radioactive substances. Examples include paints, lighter fluid, fireworks, tear gas, oxygen canisters, and radiopharmaceuticals. However, there are specific exemptions for small quantities (up to a total of 70 ounces) of medical and personal care items in your baggage, as well as certain tobacco products carried on your person.</p>
                    <p>26.2. GateFare US LLC reserves the right to unilaterally cancel any booking and issue a full refund to the original payment method if fraudulent activity is suspected. GateFare US LLC shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the cancellation of a booking due to suspected fraudulent activities.</p>
                    <p>26.3. Disclaimer of Warranties: TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, GateFare US LLC DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, SUITABILITY FOR A PARTICULAR PURPOSE, TITLE, UNINTERRUPTED SERVICE, AND ANY WARRANTIES ARISING OUT OF A COURSE OF PERFORMANCE, DEALING OR TRADE USAGE FOR ALL GOODS AND SERVICES SOLD BY/THROUGH GateFare US LLC. Applicable law in your jurisdiction may not allow the exclusion of implied warranties, so the above exclusions may not apply to you.</p>
                    <p>26.7. The services offered on the Platform are not available for purchase by residents of Hawaii, and the Platform itself is not intended for use by residents of Hawaii.</p>
                    <p>26.8. No Agency Relationship: Nothing in these Terms and Conditions shall be construed to create a partnership, joint venture, employment, or agency relationship between You and GateFare US LLC. Neither party has the authority to bind the other in any respect unless expressly agreed in writing.</p>
                    <p>26.9. Severability: If any provision of these Terms and Conditions is held to be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms and Conditions and shall not affect the validity and enforceability of any remaining provisions.</p>
                    <p>26.10. Modification Restrictions: These Terms and Conditions may not be altered, supplemented, or amended by You through the use of any other document. Any purported changes or modifications by You are null and void unless expressly agreed to in writing by GateFare US LLC.</p>
                    <p>26.11. Assignment: You may not assign, delegate, or transfer your rights or obligations under these Terms and Conditions without the prior written consent of GateFare US LLC. Any unauthorized assignment or transfer shall be null and void.</p>
                    <p>26.12. For convenience, these Terms and Conditions may be translated into other languages using machine translation tools, including but not limited to AI-based systems. Such translations are provided for informational purposes only and may not reflect the original meaning or legal effect of the English version. In the event of any discrepancies or inconsistencies between the English version and a translated version, the English version shall prevail and govern. The legally binding version of these Terms and Conditions is the English version.</p>


                </div>
            </div>
            <Footer />
        </main>
    )
}
